alpha = { 'a'..'z' | 'A'..'Z' }
digit = { '0'..'9' }
plus = { "+" }
minus = { "-" }
mult ={ "*" }
div ={ "/" }
pw = { "^" }
lparen = { "(" }
rparen = { ")" }
underscore = { "_" }

identifier = { underscore* ~ (alpha | digit)+ }
numeric_constant = { digit+ }

expr = { sum }
sum = { product ~ ((plus | minus) ~ product)*}
product = { power ~ ((mult | div) ~ power)*}
power = { value ~ (pw ~ power)? }
value = { numeric_constant | identifier | lparen ~ expr ~ rparen }